trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildGoService
  displayName: 'Build Go API'
  steps:
  - task: GoTool@0
    inputs:
      versionSpec: '1.16.x' # Specify your Go version
      addToPath: true

  - script: |
      cd todo-api
      go build -o todo-api .
    displayName: 'Build Go API'

  - script: |
      docker build -t your-docker-repo/todo-api:$(Build.BuildId) .
    displayName: 'Build Docker Image'
    
  - task: Docker@2
    inputs:
      containerRegistry: 'your-service-connection' # Define your service connection
      repository: 'your-docker-repo/todo-api'
      command: 'push'
      tags: '$(Build.BuildId)'

  - stage: Deploy
    displayName: 'Deploy to Environment'
    jobs:
    - deployment: DeployGoService
      displayName: 'Deploy Go API'
      environment: 'test' # Change to your environment
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo "Deploying Go API to test environment"
              displayName: 'Deploy Go API'
